### ISSUE TITLE
How do i use this?

### ISSUE THREAD

**Issue by ededs** [sh-dave/atlas-unpacker#1]
Hey, i have not much of a clue about coding but need to unpack several atlas files and stumbled upon this github. 
But i dont really understand how to use this

**Comment by sh-dave** [comment]
You need to have [nodejs](https://nodejs.org/en/) installed. I use version 16, but it should work with older or newer ones as well. Then open a shell/terminal where you have your libGDX atlas files and corresponding pngs and just type `npx @sh-dave/atlas-unpacker some-atlas.txt` (they usually have a *.atlas or *.txt extension). After this you'll be asked whether the script should be installed, just answer yes.

```shell
Need to install the following packages:
  @sh-dave/atlas-unpacker
Ok to proceed? (y) y
```

Then you should end up with an `unpacked` folder containing all the separate png images.

**Comment by sh-dave** [comment]
@ededs did you manage to get it to work?
